apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.domain }}
      tcp:
        paths:
          - backend:
              serviceName: weechat
              servicePort: ssh
          - backend:
              serviceName: weechat
              servicePort: relay
